#cloud-config
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - ca-certificates
  - apt-transport-https
  - curl
  - gnupg
  - lsb-release
  - unzip
  - jq
  - docker-ce
  - docker-ce-cli
  - awscli

runcmd:
%{ if initial-manager == "true" }  - docker swarm init --advertise-addr ${initial-manager-ip}:2377 --listen-addr ${initial-manager-ip}:2377%{ endif }
%{ if initial-manager == "true" }  - aws secretsmanager create-secret --name Docker/worker-join --description "Docker swarm join token" --secret-string $(sudo docker swarm join-token worker -q) --region eu-west-1%{ endif }
%{ if initial-manager == "true" }  - aws secretsmanager create-secret --name Docker/manager-join --description "Docker swarm join token" --secret-string $(sudo docker swarm join-token manager -q) --region eu-west-1%{ endif }
%{ if initial-manager == "true" }  - ECR_REGISTRY_AUTH=$(aws ecr get-login --no-include-email)%{ endif }
%{ if initial-manager == "true" }  - eval "$ECR_REGISTRY_AUTH"%{ endif }
%{ if initial-manager == "true" }  - aws s3 cp s3://dockercon21-docker-compose-config-bucket/docker-compose.yaml .%{ endif }
%{ if initial-manager == "true" }  - docker stack deploy --compose-file docker-compose.yaml dockerconstack --with-registry-auth%{ endif }
%{ if new-manager == "true" }  - docker swarm join --token $(sudo aws secretsmanager get-secret-value --secret-id Docker/manager-join --version-stage AWSCURRENT --region eu-west-1 | jq -r .SecretString) ${initial-manager-ip}:2377%{ endif }
%{ if worker == "true" }  - docker swarm join --token $(sudo aws secretsmanager get-secret-value --secret-id Docker/worker-join --version-stage AWSCURRENT --region eu-west-1 | jq -r .SecretString) ${initial-manager-ip}:2377%{ endif }
