#cloud-config
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - curl
  - unzip
  - jq
  - docker-ce
  - docker-ce-cli
  - awscli

%{ if initial-manager == "true" }
write_files:
  - path: /etc/docker-compose.yaml
    content: ${docker-compose-b64}
    encoding: b64
    permissions: '0600'
%{ endif }

runcmd:
%{ if initial-manager == "true" }  - docker swarm init --advertise-addr ${initial-manager-ip}:2377 --listen-addr ${initial-manager-ip}:2377%{ endif }
%{ if initial-manager == "true" }  - aws secretsmanager create-secret --name Docker12/worker-join --description "Docker swarm join token" --secret-string $(sudo docker swarm join-token worker -q) --region eu-west-1%{ endif }
%{ if initial-manager == "true" }  - aws secretsmanager create-secret --name Docker12/manager-join --description "Docker swarm join token" --secret-string $(sudo docker swarm join-token manager -q) --region eu-west-1%{ endif }
%{ if initial-manager == "true" }  - ECR_REGISTRY_AUTH=$(aws ecr get-login --no-include-email --region eu-west-1)%{ endif }
%{ if initial-manager == "true" }  - eval "$ECR_REGISTRY_AUTH"%{ endif }
%{ if initial-manager == "true" }  - docker stack deploy --compose-file /etc/docker-compose.yaml dockerconstack --with-registry-auth%{ endif }
%{ if new-manager == "true" }  - docker swarm join --token $(sudo aws secretsmanager get-secret-value --secret-id Docker12/manager-join --version-stage AWSCURRENT --region eu-west-1 | jq -r .SecretString) ${initial-manager-ip}:2377%{ endif }
%{ if worker == "true" }  - docker swarm join --token $(sudo aws secretsmanager get-secret-value --secret-id Docker12/worker-join --version-stage AWSCURRENT --region eu-west-1 | jq -r .SecretString) ${initial-manager-ip}:2377%{ endif }