#cloud-config
package_upgrade: true
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - curl
  - unzip
  - jq
  - docker-ce
  - docker-ce-cli
  - awscli

%{ if initial-manager == "true" }
write_files:
  - path: /etc/docker-compose.yaml
    content: ${docker-compose-b64}
    encoding: b64
    permissions: '0600'
%{ endif }

runcmd:
%{ if initial-manager == "true" }  - docker swarm init --advertise-addr ${initial-manager-ip}:2377 --listen-addr ${initial-manager-ip}:2377%{ endif }
%{ if initial-manager == "true" }  - aws secretsmanager create-secret --name Docker/worker-join --description "Docker swarm join token" --secret-string $(docker swarm join-token worker -q) --region eu-west-1%{ endif }
%{ if initial-manager == "true" }  - aws secretsmanager create-secret --name Docker/manager-join --description "Docker swarm join token" --secret-string $(docker swarm join-token manager -q) --region eu-west-1%{ endif }
%{ if initial-manager == "true" }  - docker node update --availability drain ip-10-0-1-5%{ endif }
%{ if initial-manager == "true" }  - docker stack deploy --compose-file /etc/docker-compose.yaml dockerconstack%{ endif }
%{ if new-manager == "true" }  - docker swarm join --token $(aws secretsmanager get-secret-value --secret-id Docker/manager-join --version-stage AWSCURRENT --region eu-west-1 | jq -r .SecretString) ${initial-manager-ip}:2377%{ endif }
%{ if worker == "true" }  - docker swarm join --token $(aws secretsmanager get-secret-value --secret-id Docker/worker-join --version-stage AWSCURRENT --region eu-west-1 | jq -r .SecretString) ${initial-manager-ip}:2377%{ endif }